### ISSUE TITLE
Running in Spyder. Please Help!

### ISSUE THREAD

**Issue by Akashgarg08** [aarivan/Bayesian-Regression-to-Predict-Bitcoin-Price-Variations#2]
Error -  print "The MSE is %f" % (MSE)
  File "<ipython-input-1-73c57e4073f0>", line 154
    print "The MSE is %f" % (MSE)
                        ^
SyntaxError: invalid syntax

Tried Solution :-

if done this  - print ("The MSE is %f" % MSE) 
then error - 

 ( for i in xrange(0,len(train1_90.index)) :
  trainDeltaP90 = np.append(trainDeltaP90, computeDelta(weight,train2_90.iloc[i],train1_90))
Traceback (most recent call last):

  File "<ipython-input-19-7556033f4d5c>", line 1, in <module>
    for i in xrange(0,len(train1_90.index)) :

NameError: name 'xrange' is not defined )

Please Help!

**Comment by esquire900** [comment]
This script is python2, to convert it to python3, run this in your commandline:

`2to3 bitcoin_ab.py -w`

**Comment by dothanhhoangvy** [comment]
How to make 3 file _90.csv, _180.csv, _360.csv from dataset, all data in dataset are using for what in this code? I don't know it please help me!
